swagger: '2.0'
info:
  version: 0.1.0
  title: ChOrEgg
  description: |
    **This document describes the ChOrEgg API and its operations**

    You can try all HTTP operation described in this Swagger spec.
    
    Find source code of this API [here](https://github.com/dannyshay/ChOrEgg-Web)
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/users/:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        200:
          description:  List all users
          schema:
            title: Users
            type: array
            items:
              $ref: '#/definitions/User'
        400:
          description: Failed to retrieve user
          schema:
            $ref: '#/definitions/Error'
    post:
      tags:
        - Users
      summary: Add a new user
      parameters:
        - name: User
          in: body
          description: The User JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      responses:
        200:
          description: User created successfully
          schema:
            $ref: '#/definitions/User'
        400:
          description: Error adding new user
          schema:
            $ref: '#/definitions/Error'
        409:
          description: User already exists
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
          - Users
      summary: Update a user
      parameters:
        - name: User
          in: body
          description: The User JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      responses:
        200:
          description: User updated successfully
          schema:
              $ref: '#/definitions/User'
        400:
          description: Failed to retrieve user
          schema:
            $ref: '#/definitions/Error'
    
  /api/users/{username}:
    get:
      tags:
        - Users
      summary: Gets a user
      parameters:
        - name: username
          in: path
          type: string
          description: Username of the User to be retrieved
          required: true
      responses:
        200:
          description: User retrieved successfully
          schema:
            $ref: "#/definitions/User"
        400:
          description: Failed to retrieve user
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags:
        - Users
      summary: Deletes a User
      produces:
        - application/json
      parameters:
        - in: path
          name: username
          description: User ID to delete
          required: true
          type: string
      responses:
        200:
          description: User deleted successfully
        400:
          description: User not found
          schema:
              $ref: '#/definitions/Error'
  /api/users/getUsersByHighScore:
    get:
      tags:
        - Users
      summary: Gets users by high score
      parameters:
        - name: numUsers
          in: query
          description: The total number of users to return
          required: true
          type: integer
          format: Int32
      responses:
        200:
          description: Users retrieved successfully
          schema:
            title: Users
            type: array
            items:
              $ref: '#/definitions/User'
        400:
          description: Error retrieving users
          schema:
            $ref: '#/definitions/Error'
  /api/items:
    get:
      tags:
        - Items
      summary: Gets all items
      responses:
        200:
          description: Items retrieved successfully
          schema:
            title: Items
            type: array
            items:
              $ref: '#/definitions/Item'
        400:
          description: Error retrieving Items
          schema:
            $ref: '#/definitions/Error'
  /api/items/getItemsInTimespan:
    get:
      tags:
        - Items
      summary: Gets some item sets within a specific timespan
      parameters:
        - name: category
          in: query
          description: The category in which to retreive the item pairs
          required: true
          type: string
        - name: timeSpan
          in: query
          description: The timespan in which the items dates are to fall
          required: true
          type: integer
          format: Int32
        - name: numPairs
          in: query
          description: The number of item pairs to return
          required: true
          type: integer
          format: Int32
      responses:
        200:
          description: Item sets retrieved successfully
          schema:
            title: ItemSets
            type: array
            items:
              $ref: '#/definitions/ItemSets'
        400:
          description: Error retrieving items
          schema:
            $ref: '#/definitions/Error'
  /api/categories:
    get:
      tags:
        - Categories
      summary: Gets all categories
      responses:
        200:
          description: Categories retrieved successfully
          schema:
            title: Categories
            type: array
            items:
              $ref: '#/definitions/Category'
        400:
          description: Error retrieving categories
          schema:
            $ref: '#/definitions/Error'
  /api/difficulties:
      get:
        tags:
          - Difficulties
        summary: Gets all difficulties
        responses:
          200:
            description: Difficulties retrieved successfully
            schema:
              title: Difficulties
              type: array
              items:
                $ref: '#/definitions/Difficulty'
          400:
            description: Error retrieving difficulties
            schema:
              $ref: '#/definitions/Error'
  /api/getEnvironment:
    get:
      tags:
        - Other
      summary: Gets the current executing environment
      responses:
        200:
          description: Environment retrieved successfully
          schema:
            $ref: '#/definitions/Environment'
definitions:
  Environment:
    type: object
    properties:
      environment:
        type: string
    example:
      environment: 'PROD'
  User:
    type: object
    properties:
      username:
        type: string
      createdDate:
        type: string
      lastSignInDate:
        type: string
      totalRoundsPlayed:
        type: integer
        format: Int32
      highScore:
        type: integer
        format: Int32
    example:
      username: testUserName
      createdDate: 01/01/2016
      lastSignInDate: 06/15/2016
      totalRoundsPlayed: 75
      highScore: 15
  Item:
    type: object
    properties:
      category:
        type: string
      name:
        type: string
      date:
        type: integer
        format: Int32
      image:
        type: string
    example:
      category: People
      name: Winston Churchill
      date: 1874
      image: https://upload.wikimedia.org/wikipedia/commons/3/35/Churchill_portrait_NYP_45063.jpg
  ItemSets:
    type: object
    properties:
      itemSet:
        title: itemSets
        type: array
        items:
          $ref: '#/definitions/ItemSet'
  ItemSet:
    type: object
    properties:
      name:
        type: string
      date:
        type: integer
        format: Int32
      imageData:
        type: string
      category:
        type: string
      image:
        type: string
    example:
      name: Winston Churchill
      date: 1874
      image: https://upload.wikimedia.org/wikipedia/commons/3/35/Churchill_portrait_NYP_45063.jpg
      category: People
      imageData: /9j/4AAQSkZJRgABAQEAyADIAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAFeAV4DASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAwECBAUGAAcI/8QAQhAAAQMDAgQEBAQDBwMDBQEAAQIDEQAEIRIxBUFRYQYTInEygZGhFCNCsVLB8AcVQ2KC0eEkcvElU5IWMzRjotL/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABAX/xAAnEQACAgICAgIDAAIDAAAAAAAAAQIRAyESMQRBEyIyUXEUYYGRsf/aAAwDAQACEQMRAD8A91T7123OlG9KaayNDc1xya6lOKBqGEZoZTRpppEnFY1ANBmk0e9H086QgGtZqAaTTTRyN+tIUzWs1AIMDNdpNF08qXTPy3oWHiZXxHeGy4hbuuEhptgqnOSowRA7D71miOK8fui6ppy2ZXgeYClakDYQcgd8TWv4vbu3HFwG1uaEtpKS1EpVJkknYRUV3h3GkJ1WLCQoiVOOmJ+uTXn5m3J0epgqMV6Iltw5VgrzHX2mWk4UtxPqxy+vIUa48TW9uxpZburpasQydJPLlMUH8BfOoW3f3YU6n40hI1DsORHtULiXhK4cZWm2uwpKwIRqUCr74qMVss+MvyGO+JOFX/maOGvKdaBQXHDrKswRq5ZH6omub4bw3ioQlwuMFIKi05cwQDsdI+ET1qJwKy/+mn3zf2SHWlga86EhM5J/jzBitbaW/AuMWf4nh6/NZ+OGlZB7g5B7HaqNKxXLjr0QWOEcEtU/lcHYXpE+aoEif+4/EabcN8PcuEsJ4SzcOyVJ8u2bBAHtke5imOeGUcQDn4DiVw0/qKiLrWHWEnZIGDpzy7ZoNv4ZvuGK9Ll1BB1PIeSMcsEYgZzQba6BHg3dljbeDbZY81mytLV1RMqUglyPcK3+dWrXD7LgaC4pCdMfmKUCR2O8ijWSGxaITcPuuafiKzBHYxWe8R2/4a1W9Y8S0rKQlCbgl1pSjsczGAoT1zTerI7lKm9Fwrj9o9lhbDzc58lz1Y5ERiBvJqtv+MpZS4pbbDCY9Jubwa1f6QCQPnXmLPEQHjdPu8SSEqCC/a6HFN4IJGsgAEz6pnAol6pq4u/Lc8W3rTqfSq2vbZTLqUASjCTpOrkRvqk86PFvspxjF0jW3903eMG4uGuDOsrkhxxamT/pUIVv2onCbq4HD2iw1auW8EpJdNxGdyVDVE9Cd6w/EfD6ENNXqRdLDiQBCfy9Qwr1ElUAjn+2aJwfhSeLXyGx+LWgeorRd5PXOAkY3ExnbFbiqtMokbn8XdWCVqVwgKUoQv8ACJlspmY0rUNM9jzFCt7fgnEXnHHbcWDyiZLaHmHAf9CoPt+9TuH+Fb0socs7u9tVFULTcXClpA6gL1FXbMGK1LFmzwlrzHHPNd0jU4oQpR6wNqVRlVk5Tgunsi2HBeHMI1i4uX0EiPxC/MGO5E/erL8RZWLOhCQlESAlOJ/3qovvECWvSzbLccO6BK1x2SJzjnFY3jXiDjYttaha2LREFy4ckkz+lAwekZ5zTJ+kJwlP8mavi3i1hhtXl3LbfYt6j/wO9ZJ/xy+ka2XW1g/wb+8GvPuI+ILtbq9TzVwCSCfwyEj2lIBP1qlVfKdWCUqQvmpKv5VVYW9sonCOqPVGfFlpfK8q4KWVEwSkaUkkxBG2Z3EGlHE7cebbqVKUDWptRktgkgLSrmmfmOfOvKzdLUhWqCQPi5ipB4i+oMF3UXIKdR5pIz/Ki8BvkXpHqTd6W/8AplHzWiNQKYJg80j90/Sri0UnSlCFBROUuqVgJ6Acj79q8g4fxa6Y8v8ANKCkjSTJTMc+xrS2/ia4bUiQrElQKpSe+dxH7UnxuLM0prR6u0zo8goWNSYToFW7MOJEiI+1ZLw34kTesKQ3atJ0pklAUARtjl961Nm+hbqfLVqJnWj+E8h2NdEZrpHDPHJfkSfKAjalLRjajxJxyxSqRIqiZFxIZR2H1pumDUlSMU0o+lPYrRGKedCUkipcAUxaAqKwtE0YJNcedN+dccdaUpQvKkO0Uk7ikkCgYQ70gNN1SSI2x71xVHvQs1D9WK4GhlVJric0TBZ600kRQ9fOu14igEdjnQLy/Y4dbOXVw6lDSBkkUUqSEkrwkbq6VRX99bcS8toIddaQrzEqbwMDeankmorZXFDlIiMeIbV7U4xeWZUpUrlSuZ6xO1W1pxBKlaVLU44RghWFZ/TO9Yu+4Wq7eCWC+pGyQXjDSf8AKDIk/Kn2tn4iZJY4fdadJlJcQlaVYM42GY71xpuzuljjRa+ILd5xHnMM3KH2vUlTSdSgBzio/COIcRYeNtfXCfMACkK/DkodnqRt2irCw4rdIQ3/AHpw5fmtqAUtAICD/t03q2XYWd8ygo/LWEnTrEYI/brQq+jOdLi1oius3lw8lNxaW9xbKB9QJCknlIPLuKqVWTPD79tbLbCNRCilaIIIBGSCORPWa1FvbDhtmEkqUlICUhSso7TucxE0G4t/zFOOaEiQlAWPSTyzyzWcH/yTjl9PoRhbhZChpfS3mCuVCD0gZpGOJ2jwfA1IWgSpJMkjqOtc6001bqaUtLCmhKFpxCQYGOgP71QKvnAlYuVITBKVKUJUyvlt8QPLrNZviaMVKyN4kcWyh/S+6pKlJ1JC/Ug4EAc0xJj7isPfcZU1NlcJdbWk63ELJUdBAIgDAjeR71oLt5BdU23pIA/MSTkdc8xVRfW9ndttIcdaabQAhtwj1oRMBJjeOhoRkr2dKjSIdgy09xJHpCv+kLjqwrUCQFK9IIiSAmehyDyqbZvWHHOEtWfHbRdw20Chp5lGh21MCWzHMYVBGmNoiqsIeZU84laClCSlu5ZIWDOyV6cgkbSOXau4fcXtpxJu/s0pfWU+S+wvIfbBJHzEmFDI2ODFWqxZRbH2vAOI2Lq0WfEXFOJX5bjCh0iFlMgxBJxtBwRVvbW/EuGvl6zXw+6ZLgISQlIdMlJjUPScQTHMUZlfDuKIZSm5cD2FLZuAQ7GdC0bathiQeYPKtfatt8St3E2ttYXDTSUhSH2ykzBySJKTHUVNylLs0pKHRQDi1wX3ECw4xZznQp4lsEcxpBEdgQMCKkr8TutNBQZUAleJQrflJBM8t9zNWzvBOF+WWnri4YSmC601delPQExntjblR3eG8M4cEtsDiaFLTs0676xtkR/tW4yaE+SC9WZG84/xS4ZcFrbuycnzGVDVneAIx0Oc71ieIW1866t99S9ZJKlKTkJ54JhPP2r0riSg4lenil2Uz6hoC4+m1YHi9ylDpLd06tUyZgARyjNNju9FOSoyNxaPFcDIHLUMVGNs4gSQRzxNWF5eLeUY8wJJMEpH9T3qKnzkuAlDsEnKjuOdd0brZyyqxoJE6sSMz+9HaSbgBjGpOUe9K0EuEagSBEgEAj2NEU2gJ+BKs5UAQR8uVZ7MGYtnmlhKmwRyCtge9b3gXDOHM2hev3JUMpt1FKoJ7Gc/tWAt711C0oJCx/Cr/f8Anyq2trttKIQogn9CjNRyptFcdWelWvGGWWh+DwpUJTJJyT8RPOBPYRWv4X5bgC1tnzRstJ+L3rxyyvlqWlrUgIBBAnTmt/wnjZYCFBZW2MHUJO24Pao41xewZ1fRvkhRBhRjlTgFRkiozD6VsoUhclQJOZk0XzeRJFdcdo4HphCOsfSmKFNU5AJmmlfamQjEIFMMTtXFfKaGpeIFMKSwc1xPWknOaQxOKARCaSa7513zoBGEkUwrpyjBoSsgmgERS8867X1oagRNMkzQMGK6TXM8qCT3ricGsYdc3CmrZxxJJWkemNyeVZlXEr63X5dzbp81RlBZIiDyjerDjbl03aNuW4JUlwBQSYMdu9RuH8SvXGi6xwtLDWkGFQXFdidhXJ5DuSs7sCqNocjijDH5dy8tKicW7TOpW3tUu347Y3P5dopLChlYWrSr54xQ2+KcYXelp6xS2lICtMEqjmRODHMVbLtrPiVq2q9tkrJEhWyhjcKGanBN6sM6Xa/6ZQcQDN4GmeItpczAWhIcBB6E9MHBFaaxCWrVCFq1tpSIUSJ25iqNrhP4d1xyxvm7hgmFNv8AqI7Ej94n3qt4nxW7tr1DbaAnWYtnh8Cz/wC0qJBCsQr+KNqKuO2FxU9RNLfXAZvGwHUm3WRqT/CqZBB5iNx7GoT3H2m1IZeKChwFBUfhK0khST02+4POslYeJGrtI4fcrU06gkNBZ9Sgf056GRn/AMivHkX7NxYhGm5UorQpR0FbicZHIkDTIwYE0OTbsKxLSZfcY4tpt0Xds7ukAlXqEERCjyO2azTvFi4gJCW0upGkpKk6tJ3AVzzmsw3xZ9JWQpQxJScAKG4I79KhuXzbmtIBbVGAlWCP+KHxts6IqKRonn2VXGtP5brZJUnTKkctKknA55zvtWeueIKZWSh5RnBSBqT7Gd6q3uJuJUCXHC4JIWo57EdMfeoj14p5xSk5BnSleTHc8zVseH9glkSLBziqnSVG0tiv+MICVVDN3coXrgiDIPSgOXnnKQhDNtbjCfSV79SVE1zLLa0ParlKNCkpAUQkrmZA7iAR1yOlX4JEOb9Gh4rxd5V41cqhzQ2gIJVPoAj5ieR2xVzwjxXYLCnbuzKXmkakPMKUlQM45/LmN6wjbgAS06ttzopCpCZ7/uK0vB/Dj/EiHeH3NsvMKSt0IUzzn1YUOeJqcoJIop3/AA9NsfEfDivK7hWglKiu6Vo1TMAKz9PlScQ8SNOLUi2Qt8bkrJabxvjdXSTivMHrG/sry5SstofaStwoJUQ9p/8AbPOQZzG3WpqX27try0BSlJwUIVKwY6bmai4v0wrHC7ZYcc4yhwLQlxtalCPLQdKAPl/xWYRbpv3y1+MQhwJK4VCUJG6lKMwgdzPKrZNqbh7ylFxJJ0DUx6p+u9BPC7W31KU75qkEHSAACQcTnlG1PBqA0o30RF8N4ewNYuPxKFCUvAFGrl6QfUR3wDUN9+0QjyGbYuZkIUshKjsMA4qZ/d7V0455bqELSZWpCgo/6if66ClPDGmUFSkobQVfqWfp1VVVNeyXxsqLouXK0sssjUgAaWEbn9SieWwHQACovmrbVCzrzpmcz27d9q0Rsy+2tKIt7YEanXU6U/6UDfsTNVV3ZhC1rU2tTZA0IUCnHIqJ2nnFUjJPTJuLXRHUpK5KxEH4hyNFBLCkhY1kiUrjdP8AOgIV5DmhWUnZShGrGcVJW0ppqWfzbcHUG1HKT2+1FhLXhvq1FxwpaA+PSSVdq2fDLlEBCNWlGRIAMbf171gbO7QtSStpMgQJFaewukoMoaSJ5iufIUq0ekcI4gsOI0pCm1fEAfh6GtAl0qg5GedYLglyQ+2ELhaTBHUdD2NbRhQVoKJJJBBPId6rido4cqpk4ap3NOzTAoU4rAqxBiKnaaEqe9OUsdaHM4oitBw5vNcXD1pAntSacdqUYd5kb0nmZocHnSGgYcpwmkmk5U0SCKwRxz0oZHan8qQiZPKgYGaarFONIAVEJG5rDIh3CBcOJbguJQr1eqEpP+btSt8e4bYXIt7m8aaWIISreDsT0npUK+vl29lcPK0tI1QCrny2515fxLibrxcRbI0FZl24cMkknkOvauJtuR6GPCnHZ7qtbLrKSCkEg6FCDWG49cXdhdKctXXUPp9SWjs6gbpT1MZjptWCsOMXNiFJfu7q4bmShT0qT8+Wwx9qnueMkuoSzd+clMmFOwvAGIOCDtsa01J9IbHj4eySrih4g5+I4NdlPEQohFu+9odUnfSlWyiDtJ2jY1TcQ484p8POLct3NX5yNBQSrGY2SvlPPBIOaiP8Ytbt54F5CmnfUpJSCkOfxciD3EdxUd1tNyVq8xt5tYI8p1U6Ry0qnPz608Y62PS9D7y/W5cIuF6VOHUlThMeYmefKYjbn1FSV8cdY8ht1sr0BJ/NUZkcsbEYI5dQRFU3oSwpDyVqIMgGQP8Af96Z5epiAVYgKCjt3+mJp+KFbZKvnVO3BdQAlxXqUAI1SOX+1Vr7ijC4zzkRNPU+6w2ELaUpKSUpByQOmKe5+GebQXX3LVSkyn8vzUqjpke3Paniq7FbK1y4W4YI1HYc6AXNo2OaM4z5X5iAuJlKlJ0k4nbkYO3QioygTOB8hAqySJNsU5Eq2NPQoNqC0qhaTjbJoXKRMzvypR1jNMxbDIcTAlMqERsfrR2b99k/lrOkGQBt3oCGyvaY3J2o6GCdt+tK0qDEtrfjV2psoX5rjcZzqTjsdqsfxlrdWoU4nyVTBXoBSo9zuP2qgTbhIg5ozKSlUJnuOtRlBei6bov3OJWzTQbdZv3ZyNRQpJA2IUkz8jP71HN1YebLaVBuAVJcQrPYDeq9TAQ2hQJQFiUQrBEwfoaEWFj/ADHoc0nBDpsv3uPKcYSyy2lLaT6ZVCUeyBA9yZNDbcttYdublpw4A1mPnA/mflVGWMEZT2IxTAzo9QKSvr0oqCA2XtzxSzaUrQrWUiAEJnVG2+AKrnuLuuI0paSlChEk6lVBTpSopVGg7965bSiz6FBenlzplFIDZGuBJK1Oaz3ERNJoSUhYUU4z3rnEqKDMGDgCnNAJhRyMYNV9EUtk2ytj5gLmoKT8QUDj351pbNSW0gGQgp6bZ/r61n7dTh/SAkRia0NusLQgMpLpA9WhPpmOZ26/SoZB0vRqeGtoeeQpMJcDQUVfwq1QP51tOHXHmWqVEaXAShYJnIrIcGZDTaHXlwpUeYEGSTOw57fc1quHMuItpcTpWslRSTJEnAPeKOOzlzUyz8+m+fzmgBKtuVcUme9Ws56Cl6TvSeZn/mmaDHekKSOVFAdFwGwFlUqyI3wK5SeW09K4qz/vTSo9KYwikg0wp7U4qMHNMU5HOgAXTNIU/egruUp5jahG8REA/egEkkU39+VDTcpVzoqVJMZoUGxhTNMLaiDBbTGfWYFSIBHWmqb1COv2rUFMwPiS8ZZUvzMNoAJXEkYxI95ivN3+IKdfUtlpSsEyqcDmQB+9afx46h/jTjTWoNoPqUP1GI+giss1aOrXBC20ujScbp3z9JjtXKoq3Z6sb4oETdXTSiVaWm+Xc8h3qqukLDigsqK8ylRnT2PetJccQRbhTFkFAtghK0jKMZVqOxP8X0rLuLKhCUwOszPzNWxonkfojLOlJJmNye1aRNsnh/CmEOsoLikhxcjIUcj7RVHZ2n4/illZif8AqLhto9gpQB+1avxKvXxV5EelLitOIwDAxWyvaRXxYp22VjC2lo9S3GnB+tORnnEY+tILV93QGG1uFXpRpRlZ5x/UVGW7oBSnf9qNb3ry3FJyCsFKjOEojKQOQPPrS0+0PKiFdoctwqRqJwCnY+x5ioSnllRc1HUqCT7DpVxdMLWhS0pKhMkTvVWqJP5RJ71XG7RzZItPYESoASqJ1Qe+9cEHlPzopCo9UJB2iubTqVmSKcnQMNE4GfajN25GSn65NTmLeUgxRw0qcCesCkcyixkFDKv1E/8AbUtDZ5JAA65qU3bAEE/IVIDKdoJA5xSuQ8YEJDalCZJBpS11IAnaph0pBSD2gVHc+JQB25GlKVRGUkDlH86GPR1nsaIoEHqaQkHf5TWAKHlfqAI7ilK0HGkg/wDdTCnE/augif6msNQxZQQU6F9/UKRtCTgjGMEwfrT9M9CB2pUIlXUd6InHY9aRAGnE7gb0BxAWUtwRnUoAVYscNurghLCFHr5e9Xlh4O4m7A/u+4bK4Op3E9N8j6UE7JyaXbAeGrBD18guGA0Q4oAaiVDCQBz5k1tbmzbuy7cFqFrIMbkAkBI6TAH1qRYcCubC3Sxb2akNBPrcSpBU4eWCcCdpOec7VbWdi7+JaccCEtsqK0N6yo+YR8a1cyOUCBPamUOXZyZMu7QbhnB0sQTMjB1DAParoMCByAxTWlpQj1K1K3J70X8SiM1WMaWjnc7G+TFd5XUUqrlA5imm8QMmKNC2L5YpFIihLvkDOqgm+SonNagWTTcoB3FMVdoHP71lXuKFpakr1pWORFRFcfbG6/vScrKONGvXfNjdQqvueLNoSfUPrWRufESIMKrOcR8REgpCt+9FMZQNffeJG2p9f3qmV4xRr+MVgLq/ceJlRqFJyZNbY/A9fs/FLTkDzQfnV7a8bbcHxjtXgyLhxsgpWcVaWniK6t4GqRRX+xJY36PeWuJoIHqFGF8kmdX/ADXjVt4yUBCyQdqtLfxk0pQ1OJgmMz/KjoTjJMfxrh6XfEF4khZ0ulYAE4InUf6zFUquH3JLfpIcfJbbBwEJ5qJ6x9K15UxeNPXhWlXm+UFuIMKcyducQEie1SXDZN3tu9cZebZX5baR6UJAMn277kkVwSdTdHrQk3FWeZcSsmbRDgcuy64kwhtpBDfclR5D7ms6s6jJPetJ4kdev7sulJQFKlNuJKk4ka+QMCY3qr4rwm64Q+1aXKUpuFoC1ICpKSSQAfaPpXTjet9k5rZH4W+my4vw+6KgPKuW1qJ/SAsfyJPyrQeImHbbiDiXJKpIKjzzvWScAVqRun4Z69a9Aun0+IfC3D+IJAN00Pw1wBv5iQAT8xCv9VDL6kdHiSTuH7MkpfoAOkgbSJpUXTiQoJUlsERIATVqrw+8bFy5bV8ABKZFRuENNo4iyt1KVJSqdJG5jE9RMYoWqKSi7LM2ikpS0qC4lA145xO1Vt3YnVqSAlXUJq5stTzzq16irJJPvTHo8xedRB0ikjKhJxt0ZhVguZUFGj29grUNQgfvWhTbJWkAijC2SAYEBI/qTT82T+JFWm30iCCPenFnSnqJiOtWJt9I2zPKnC3VMwQBmhZSqRA0BAA0eqKY56QCQfcGpt1coYQUqSERzAqjcvUqUYUIP0P+1HbJ2K68onHxUBb6k6gRntsDXOXbIGXEEnpQDc28x06CikzX+mNduCOZnemJuxOetKXLZyZgg96jqaaJlB+hp1TJu09MsW3EuAGN6MQAINVzSVIIgz3qwR6vekkqLQb9j9A0jpRWWxIMUMEkwNhvNNN+00dJMxzpdvoe0tm+8LstsWv4hwAHWOfIf0K0/wDfTOpYCkbatM5MV5Q54heRwxSEEohxKkgDBVmqU8Wu4Op9R9Mb1TGmkebnjzm2e0veJ7ZJjzEwDO9APixgf4qfrXjC764UZLhzimfi3iMLP1qtsj8J7QfFrB/xRQ1eMGB/iADlmvG/xLpj8xWaYp9wjK1fWimb4T19fjS3E/migueNmNvMnv1ryIrWcaz9aYVZyaNm+FHqL/jloGNfarXhHHTfJUtOogCvG2/iBFeq+DWR+A1QDI/nWr9izgoovrq4LWhniuly1dH/AE9+3tnYK6e9ZPxBwi6sV+YlRLasoWjKSPlUDw/4kXwwGxvgX+Eu4WhQ1eTPMf5eo+YrUpuBw1CGHVC54PcYZcJ1eUTsCenQ1yVKDPSqGRWecvP3AUQomRURa1HJM1rPEPBhZrNwwdds5soZ0msq4kpIED5VaLTVo55Q4vYI9KbO9OKSOtJG+DTCDRz2pNvenRjmKSN6wRJPSlkg7x3pQnPSkgde9Yxu/CvEWlcN/BtodLrUr1LMhRJ2H8ITOBv6lHnVmVlb7y1vOBbzwQFBOQlOZHST0rBcKvF2N8m40SAkg7xBH3rYXl08q3YumwpAWgr0qH6jBA+kGuHLBqVnVhaaovOD2dmlzzWLNlp1xPlMqeT5hUlMFSyDneM8yd8RWb8Q8Ns0+KWnEPi4c8xlbiVDUpRK9RE7EaNSlcgIT0q3t7tvhdkXnFpCkJOpbgBSiSIEblROyeg71kbq7fecU+AS8+SkKcPqAJ1KUTyUSZP0GE0cdt2FqmZd5GlalJyFlS0SIkaiBjlscVovBN6tjiTljqIbvAAByDqQSg/OSn5iqa90q0AuKX5SA0nG6UkkQOQknfrVp4U4U7xDjYS28LdFsg3T9wRqDCEEHVHMzgD/AGNdE9wEg+E+RoLhx5SHUk6QsiUkxMc6qW30N3QUhllwjZRMwetex2Vi9xSwW9whm0tgVKCbp1Ic8wzuMZAPOYOYEQT5n4ntb+y4ity+aY/EqUpS3WQEocTiISBAjJPMz2rnipHU/KhkdJCW6PJslFRycz3oTTMqCjgD606zcFzZNqI2378qmBoEAhJGefSmGWwIRMmRP7U5PwBPPnUpNsSr4eUnvTS2U5ER7b1gIYWyASIzia4lTbakoAB6nepB9KJXBI2/8VXPLKyelEzVke5WlUytOraBvVFd2jBVqU2k9cxVu8rSIHpqvfUDOxpkI4IpX7RhTRDUSDvOR71WrQttWk4I5zvVxcok60QCOYqMqSCCkGrRlRzzx0QJUBz/AN6I0swBmKetCQSQmKYBMSI79ad7JbTJrahI5TU5lWQT9qrWxKpOIFWdgnXctoUMFQEfOpTR042Avb0sOfhmyNUfmK79PpTbNDd0sIKBqPI1XutuLunFqClLUtUkDuakw/Yp8hYBDqAVECVBJ3RPIdY3xTcVWiUsjth719hTnk2yEi2ScEH4z/F9ftUM7kb05Qg00AdKZKkSYkEDrSCR/W1PiugUQDee9cdutOApQO1YAPSSkmBAExIE+3X/AIPShqB3z70cpHMUxSQDRRhrI9e0Zr1nwcr/ANPg9K8oaADgAr1PwovRZ4PKnRDM9Hn7VwW90hUYIP6h0rRcF4mmwQm1fUXuGXGEE/oPNJ+efess6n0Badqfb3EJWys/luHmdj1qUo2dEZUejf8A4ylW6vzrRwQZM+k7EVlOL8N/AXhRksq9SFxgipXA+LuAGzeVKm8oUeY5irTiRbvbQsSNYy2ojY7x86ivq6LSfNGcPCx5PmJVqBqtea8pRERmrzhj5be/CXEAK2zgGmcVtfWdAMdaCbUqZx24ypmfjPekmBFPWnSqmxzqxU5KAqTKB3UqKWG0H4tfYY+9NNIcDlWMSEulaPLWYaGyOhPTrW/4aBdcEtPORKG1KKFJAnTvnod/TGK86EAydq13CnVItkXbY8ouylTnRCdh9ahnWkWwL7AfEfEVXCENJbaaVKllLMqKZwAVK2xE+9RrFPmt24EBGqZUcZAG9ReIWrrbziFp5lSVkaiUn/md6e06WVMo1HWDJO+aVJcVR0PUioeVK3S2kgJhKNRkgH+fep3h/iBsr59rVDd0ybZZ8xSdJJBSZT0I2ODNQrghCDB0+rAPz3odo2dQBTNVauNMkl9j3nw/x953wnbW1k2fOtG0svoSmVIUOcbwdwehrFeJ3TeXrVqtRDxKnHioxoQASSZ2Gneq6wszfBA1OBW2pKoUr/VOB74q04pwlq04Gv8AC5Up1KLh3UZd9OoATnSCJ/zEAnYCuRt3tlo4VB3+yo4EPNtYQgpbSTCTuEzie9am14a89oU0kqC5IEZxiqnwrahS32lTK7dWn3Ga9B4LoXZJcxqIjFCUtl39UVjXA1lvUtJTiTGc1AueHFK3G1kBYHpT1rXglC3UThXqAxz3qsuyG39RQe5ochI22ZC6T5WtMEdJFVL8KJDY7zG1X/GCPMdIUUtr9UEQBO33rOhQaSQuAsnIneqRkVaogPDJOf8Aeq5yNgR3FTH30jAOBz61AcUN4FVQjBLCdv8AxUR1kRgx7VKUe1CVJzTonJWQ1M95JpqWMx/U1K0o1ZIk0ZtkaREdqfkQcdgmWgkE5NTLQRcNgYhQ/ekLZSk4PzotkkquUjaOlLJ6KxiR22lfi1jSI8wwPnS8ecC+OXeggJSsIhJxKUgH7g1acLQl28Y1AQVpJkd5NZ11ZedccJJLi1KM9yTWg7ZLyElSQIzAma4DlTuXOKSB/wAVU5juYron3rufelB6msYSJkb10YE0oiT350pI6/asAaBSKinZiMzSKggzj5UTA0D81Nej+GHP+kInkK86SPWMbmt94cT/ANLjeKeJDN0YkKgERigKwqnKMGmHJmlLElp5SSHQSHG9vatVw+8bu7XTI8xOyScqT0rHNuFBkffnR7d4oWCD8JnFLKNjRlRfvsfiHFKYSrzAdQ7EdatH3GruwafCdLpEOImdKudUSLpxz1oWZjMcxTWrktXGkkgOciZBNTlC1QMkOS0R7xASsyBUOKk3K5cI2Peopg/WjHrYsVQlcP6g0u+KTbfFMMOlCEFalKEAlQ09OlbTh9utn/0x9KEPWq/LdyCAtUKV8wTHaKxrLrjKwtpakLSZCk7g1sOGlLXD3NOtSlOuXCm4kglIETud65/If1Ojx1cybd2g4x5+FFpJlCk4gjEdyZ/asu6kgrIASlLmgJG5jefnNbS1ULdtDrkt+U3qQ0rJTiST3OAO3Ks5xW3LdxCxC1kah/Ceny2PeufHP0dco26Mw+FfiFoA3UQQOlSrNqFAhtMgxtR02Zfu1xhWok+1TLe2gjYTXTKWhIQfI0HBtRdbQThXpwMgc/51teJcPF7we9abWZZcS6gKERCcj5isbw1Xk3DS8gJUDjcVvrF8Pt3bIPpUEifdMVyPsrkT9GH4S4Lbilu4DgqjbkcVs+FOFtpxsx6VmKxTiFsvBKgoKSuBpGZmtMxcFtxayrKoVB3HWB1rT/ZRq9F2tSSUqBEc46VV8VfUpo+XzTnEfP2prtzqBGv07b5qBevpQhz1Akzsrn2pAxjsz3ELtJWJKiEgmeY6ntNZ65uNPMCeU/vUjiVyrWYUQDmOuZz86pXXCtZzXRCImSQ5TpVnaaCpQO+3tSLISCSaApZJ3gdKskScqCKWAImT2oKlE9aTUd5BppJBxPzp1Ek52SbRtKxKhM1KbaPmacgTyqE0/wCUcZSdxU5m5aLkhUEDY7is3syimSnUAIAwTHOm2QBugmT6hAPuCKa88FgFO0Rk0y0d8u5QRuFChJlYquyRaPKtLa4ulSPJaJBP8R9IH1IrPgFKQIM7VbcauUpuXbBjDTTxU4qPiX/skHHeT0quDRPp000FSs4s0+UgR54pkQDvRVpgxTdJE4p7JWNO24IHMGQa6BJ+9Lzg4rozRCNBxml+tKRtXAVgHDnFNO1PiBSGIzRMIyJeQO9eicBQRa4BGKwFoguXKU7xXpnAWItIxtTxOfOeXqiaYdqIR3oe1KXESrST3+1Kk6Vgk9qYrGa6dQmflWMTWX1JbKkqIUkx8qep3UieYz86hNqgkzg70ZtYzOc5oNDJk67Wl9KH0p060iQDgmohzNFbUPwpb1yUq+E9KFiaUAm470nyrs+1dE9Kxh7agjUqJMbnl1+dafh9yVtvITKYAKoOQF7n5naswgEkQBvmf3q24E/HEHHCYQGl6iTEgZ+uMVLNG4lsM+EkzY8K9DRuC0UlGtwB4hSsYST161nnPXcla5UScHqo860tsTcNaEHDysZ29IhPtuO+aZ/cznlz5TkKIKSBsRXn8+J6cVGSsruG8PP93Xd2pHpSvQlZHUSahtp1LAG2/wB69JurS3sfBirdplQK0BRUREnqawjVroEctqopWLCVpskNoDekEe8mtLwq5Uw7o5qQCQVdDWdURIIONNHZuQi8ZUokgiARSysdK0SeMWrSeIecEqSl7PKNfPelbuHG7VKYWry/SsacD3jb9qlXB8y3WNU6sK1ZBqscjySDoQQkBQCiNXciP6isnaoBKbuCtYComZjaaDxRwNoKSUhZScJOQTUZD6g5JyqYmNzULiVwVggiTHXFZLY/+zOXqyVlRVNQUjnO+aPdKkq7c6jJUAifnXVHo5pvYF5ZOopOQMVCYW86ZLhgfxVL3qE604gkokAjOKvGqOabfaDhxREqTKRiaeFIJ5+1cw80u3SxqIUsgbbVOcsELLSUYmdRjlQbo0ZX2QygKI00Zq1K4BkTsakjhOq4bbDxQhWVq30pnJj2/agPpNtdhhpxTgCAVKWmDJ7Clu+iioM/w+6tlpQSHNTfmp0KBOjqRy2/brTmR5Cwt1SSoZS2lQJJ5THwj3qRe2y7ZpNnE3DwS7dGcjYob9gIUe5A5VFbs3GiPRCfalTtbOfL5FaRwZNw8pxclxaiomNyTJqwRw1S4EE8pNS7OwIWnUMHlWktrJICRAHeubLncejz3NtmU/uBS4WUxQXOFSnAjGTXoX4VpKNhFVl2wgpKWxKjgVOHlMbkzBq4aSopSCc5jnRUcEfWRgge1bK04a2hBUsSrnU5uzShOogZqsvKfofmzzx/hDjJylRNV7zKm1Qa9EvEMlJEgmsdxFCPNVG3Wq4czl2aMyo7U1XfankQcU053rrKhrFwIuNRP3r0Xg962bfcT2rzAqKCCnEVZWfHHLZJGRVIyojlg5dEA7xQye1PVvTD3pSo05EU2YM07em5nM1jCkwdzHIUQqnJ3+lMiMc64n2omCoV+ZiBI3qQQAmZE9KhbKHKamIJU0CTJGKVhEIxiuPLIp3OmnTA3/zScT27e9KYVKiCM85rgTyGQZ61wA6x3FHaZU6tDaEFbi1BKEA/EomAB7mKDCTzxBz8MWkrIEzBzJ1CMc4wBzq04LbeIOKcUasrFviXxJ88kKT5bZOdRVAjBg7mvWPB39n1l4cQ3e3J/E8TKMuKHoZJ3DY5dNW57DFa1TYLvmaiCBBHI+9RklWzfM1pGO8SvAqFi1lKQJPWKzd/w5y1CFqaKQrptW4vOEtqdcfcGpSjtNQr/h/4lCWz8AnOxrkemd+Ka4pIwCjviIG/Wg3DpS20sGDuIq94nwRyzSpafgJgc6z12NICdI2yRzrdnTEs0XRWgZwocxUR98iSgnGBNVqLgJZAz6VbU4P6iBy3maCi0OEDilHVqXg9Ziod84TMYIHLlNSVFKmgIAjfNV1wuE/DiNtqdAKa6O+flQgJbn5Ua6SN9iNxTUpliRXSmqOWXZFAnflTltBacGSKIlHqIrkHTy5RvTWSohKbIUUxz5c6ltXDiFElZhIwFGuWgKOAAaRpbjKtxM4MT+9M3YfjskPcQeR+RbhKrhwadUzoHKB1q5XasWPG765eQFtWS22gg7OOBCcH/VJPYVC4Q+6q7Slu3acAPmEkQUAGTB5CMfOmcVv1XV6pGoKCXVuOKAgLdWolZ9pwOwqdXpE8j4LRc2jIfCnnPW64dS1RlRO5qebBtSNRAFUFpfLbQIB+tW9reKuAlKuRrkyRkmeZJOyyt2wnTIiBvU5p4BSYB74obbAU3jJPekeJbEHHLvXO/sITUOhayNx9qHpQpw9qhW72nJBjrRnbhttokGTvSLGMnZxcQ2SJ2qkveKutOFKFjSOQNRuI3yxLiF5qgcuVumCd967MOC+xuLZNe4s4sYJmc5qtdeLgJO5rijV8I36VOtuHeaQSDjNdNQgh1SK1DBJ1KyJ50ZVuA3MSK0X90FaRA2O0ZoV1wt0N6UJhI6ik/wAhN9g+QyNwjQRyqP8AOKtby2CVgbxUI25Bwk11RmmiikcfioZ3opHWhqECqDDSCD0nl2NNVvvTtvrTSPVEjPUxWMcDkVyVb4poIn3rgRtRMOUZzUxga2o6GoJP7RVpwdIcU4D0wKSbpWZulYwoKabH/FTrljTlIqDGaWLtGi7OTWj8FW7d1404My4vQn8Ulc9SgFYHzKQKzyEyQMScVccL4VxK+v2WOFtOqvgQ40UYLZBkLJ2ABjJ9udLJ6CfTAUXG/wAsgdzXInUuQRtk86iocuENMMkDzNKUrWNpjJA96cGH2lNlt0KTq9esZjO0c5qLd7ronX+xj6JXkk8hUNxEKgxFWK/gJPyqC8MkZqM0dOJ2VN4yVpKhplMqg7H3rA8Rtg4tShIIMx0PavRb/wBNo5BAUREmsNxFklGoJVrJ5jJqPTPRxO0Y59XlrPT9+9DQ9nfbBovEEwrVEEdcTVWXIVg/8V0JWgt0y6DupMGaBcCUmN6jNXGoAHf96IXJGTvQppjKVor340xzB501ggoKYzvRrgavnUMLLKwobcxVV0QkqdhXQErEETzoLiBqFHX60hQIyN6bMpyKZMVoEEqnIorbS1R6SenOkQgTEzVla6ULRB55HWizUyRqPDPDz7oGl55aWUEd5Mfz+QqksWC6pKRvtFXHiNSnH7SzbAKUJLyvdWB9h96bw2x9YK8R2peXGNnn557JDXCihGo9M9Kk29qtl0ScdKs220hAGrlzpym/NP8ACPauOWVvs43Jsks3CWgAaVavOVIAqGsFkRGTzpzSlTqJNQa9oFskJZE6eRyaj3TWpKkoMnpUptaVqIOMURdqjT5kQOoNPAa6MXfNwopKSPcVWN2i1uEJ+QrUcRQiTOfegWFulR1gZNdMctRsyyMHw/hSl4Ume9aCz4R5SCopA7mpfDktNjMY51bKUgJJB3rmnklIL2VzDCB6VBNEdtW0omBBqtveIIS4UgwQeVC/vrWjSVAgc5qKjJbQtoqOOWTaFlxCN+grOOsrKsJMVrL24DyClKc96p3LV0qkEj5Yrsw5GlsylRmVfFimqGKKEEntXOJxFepZ2URVCOVNJ+Rp+5psZIO4xiiAacGOfcUgMxSnam1jDpmp/CnvKuBPTnVfyqTZIKnkgClkrQGrRcvr18jFQvLMxv7VPatVOAAAkkwABJJ5ACvSvCP9l4Upu+4+3CMKbsp37uf/AOR8+lRjKtIEKRkfB/gjiXiS4S8hBt7BJ9dysYV2QP1HvtXuHAvDnDvD9qWbFrSpUFx1WVuHqo/yGBVo0y2y2lttCUISAlKUiAB0A5U/Ard9glJsE42olCkn4TJHXFVhW/f3K2VK8llJxp3VVwap1W7tvx78Yp1ZtiwpKW/0pXIz8xSZFf8ABsb7/YZu3vEOOB1bZZgeWBOrvPKmOojpmq9++ub11TagbdlBmeauQAjnNSbdniCgr8S2hCEqhELlRTyJ6HfFRdN/RaLq4/kyu4yoJYS3uVGs1eCEAyhIExI2rQ8YXN4hseqOQ5VS8QToSraQNo3Nc7ez0cP4ow3Fm5lQA6GNp696zbwhRIrXcTCFFSUuAgEwYgGsrcJAUSDInpmurE9ByojpcKSIwaJ+IIoChmedMUTHqFV4ojbQc3AOKC4oH2oCgeRrvUeeKKjQrmxyHFNkpn0k7UUODcH60iW0A/mJKumYq0sbW3W2tZaZQcJStYwCT3/qYrOkLbKoPCdxMxAqawstlK3yW25Jg4WrsBv8zgVoPFbtsvgFi+hbTHE2Xg04llnytbRSrBA5pKBnnqNYtKvWVKJUTudyaZQtEXndUaqzZN8+u7d+NZGBkARAA9hVoi2DYJnG+DVHwe4OE68d60aAHBG0VxZpOLpnnTk7GMnXkSY61YNAEgwKjqbDCIgEH61HTdBLsTHKueuXQi2WTyEqgEeoUINFJlWxojSw6ApRg0riyFY0kdaWmgtAVaUgg7jNLrUAYUfVUG4f/NGk5qTZQ4SpZ22zT74iWV120tSpjcncUOzQpqZJHQVfrZbcCpjAqAhprWoEwaym6pjIF+IWlSSFFKR96luXq/L9SiSOlRn20JG4qvubxKUaRg08FYG2yv4penz4So5rmFlSUx/5qA8ouvEmJ5VOslARq9q6nFKJTSRf21mVtpcPxKHOrNvhWtEkZqDZ3KQgalCKtEcQSE6UmeeBXBNSsTR5eUQaC6DEDepKh7UJSZVmvZTPRaIhRBjOc7UxQwakuARge3amLR6c709i0Re3OkijJBBJgxTQgle2KItDEpnA+laPwrwO84xfeTZ26nnD8gkdSeQqf4Q8AcT8VqS6ibTh0wbxxGFdmx+s99h1O1e/8B8PcO8OcNRY8OYDbYypRytw/wASjzNSm70hZNLRU+FvBVpwBtD72m54hpy8U4R2QOXvua1QxyrtqYpwAb1PUFSEpscVCuBqKq4zT0OEiZpHKxuDSJFCdAcRpIkHenBU8xSKxmi2BIx7lu5ZeOrVx64cFittamWyRpDmnbvzj3qXxDi1xcXKbJlJYQpQBcJj07kz7VM49YN8TslsLIQoeptwHKFDYivKPEF1xuxX+GurtzSFEFSQAVpxMHnImoStKo6TO/HBZVyl2l/4ehWfBru+uFXXmJFsDDLi5JdTHxRyEzHXeq/jzX4VOhUKUIACedXPEvECW7JtdkEm2WiUupyIjA7VX2lgjjFxbs6lANo827UFSQT8CRPMiSTypXGDahDsbHlmvtl6PPr5ClKJG3tkf71nrxqFTIOa9Y8U8As7K212rv5yQT5SxOpPOOlefXXDVrty4mO8/ajH6OmdkZxzQ5RMutJTnlJ5j5/uKGrNS7hvSdOkSMVDUd9q6YuyE1TGaZOwOOdFSkNpmM9YoaQSqnrWDicUSYg9SpJqci6Nq00oEJKnBGrtkGq9CudTbJd0u6S9btKUGCNDnl6koUT1IgdM1qszaSN7ZOjjHBbhHFfwqrhDJcbuVkaiYKghWIUIBE98bVkDwayuvXaLLBUJDS5I+R3HzmtJxNsX3hd65ulMI4hZlILjS4/EiQCFIgAEahB5weRrJIuFNLInY7d61v0c8IKSZYWvDXbRwBxsgA/EMg+xrR2oSlvAMnfnWetuLLQBqIInnVsxxZgjUtAgbwYrnzYXPaObJ48ltEy4bVBIkY5VUllSXJyQDtUG88dMs37rLdiXrdMALLulRPMxBEdPalb8XcNuTC0O2yyP8QBSfqKnHBlguiDjJei2TcKB0pFPC1KQQDUFu5bujqYUlaTzSoGpqUFLY14POka39hGQn0qkmTvFEtrjyRKlH2jepn4dC0en1UdHDPNTBSJA5VpSSVCVbIDnElwQlJzvjlRWHULBUN4qceGoQiCDnBxVNcOJYcIGdJwAaWNT6HoLcqhBPPNZ26afUCtJJJ6narpp8L9JSRnKoqYq2bU0QhKSTXRjqCMpcXsxGtxK4IIM7Vc2GpyNZCYqdd8CnSsRPOBRrLhoZcAcIA9qpLLFrRVyTQdq2SoQkZ3nrR2WigECrBpptIhGcfKjpbCRsB2rhnNkv4eaKTBoRqQtBn5UMp5Dn0r10z1aI8T8zgVIa4bd3ElLUJ5qWYApyXxbGGUeZcqwCATp7JHMnrWs4J/Z94p42EO3CRwy1VkKuR6yOzYz9Yp1SVyIyk/RnmOB2aUAvvF1Z5IMJHzqSeH2TY/KtWlQY9RJn3616O1/ZKUIhfiC4UrtaoA+k/zqh8Qf2e8Z4Wyp61dHEGUiSG0aHAOfp5/IzVIzg9E6b6YW2/tO4xYtobNtYOobTpSkNFuAOXpMACrvh39rtupSUcT4a6zq/wAS3X5g/wDiYP0mvI1PKAhckbEUxShqls/I8qzxRfQv9R9IWHiPh3GmFO8OvGbhCcKCD6kn/MndPzFNuL304PvFfOLd080+m4t3XGrhHwuNqKVD2IrVcK/tFvWglnizX4xHN5uEuD3Gyvsa5MuCa3HaL4XD2evM3KncwYParVnKRWX8O8X4bxxvVYXqHVDKmvhcT7pOfnWrZbwK54Rd7KZpRrQcbTQnXdPPFEUqE1S8SuVIB0/WqSdEMePnIbdXKHNSSfcA1lvFbKOIcObtwIUFy2qPhP8AzRLpD6pcSpwDOw2p6bV9xCXXiSEHmMVC3Z6MYKNM8wXdX9iFsNXL7CQohTYOEmc4rT+A/E7fDGuIWj74afuFh1tx39ZgAgn5U7xVwbziq7t21F0D8xP8Q6+9YC4TAiMVRRUloeW40+j09XiZtq6WXnA646kMttk6vMWowNtwJk+1bMWfCLbw+2l9hlwFoatSRKjGe9fOaXl27qXWzC0KCknuDNbO48cN3rYcXLThTC2zMTzIjr/zQ4Sh1shPHyS4OibxPwXxC+47+G4VaqLTyPOSp1UJZBMFKldZ5ZMHtVDxvwR4h4Isefw8vNmT5tsrzEiAVGdiIAJyORrVeEfHDodecWr8toBHkqMak9R0OZqw4z41X5d4sepx1vyW2woR6hCiO4BJFPGdKq2LOWW69HkGsNpO+ORqOl1TyyhsFRiYHKrzjKGeJX1q6XVguuhDz6W1OHy4HrhPxQMQOYIqNZvWHD79bVswt1fn62XroaFBAHpBQP1yQqRjlV4tVYspvpBLHgN1xF0Nrebt29YQp0grSmTAJj9MkCRtIrU8Jsr/AMOcSh648l1MNqbnW04lWJgRqTG3eqlm/trR9p5RC2wFBSFAgKSSpMRMGfiO2fal4txhfFbxjy1FpplgMQ2NIUJnb3J9gaXm2T4ym69E3jCbZzjF2q1cJtVK1tND4WyQNcdcgx2qhfZUFSKkoc0jSIAiKOAl3M99qMUy34qirTqScGkuXVMsLVMQPrircW6N4+tZ7j77YKbdsyd1DtyqyiiMpFHJMk7zXA4H03puxgYApDuR9apRKgoUpJCgSFddiKktcRvGv/t3b6QP/wBhqEDHIdqdOJAj51tMDiafhfi64tVBN00LhB3UPSoD9jXpPBr21v8Ah6b62cC21SDyKVDdJHIjpXiEjrzq+8K8YXwriwSpakW9xDboB2P6VH2OPYmuTN4kJ7WibxL0eo8SukoZWQR271irhxVzcSUx1G1aS7aTdpGtcQdx19qrHeHlCyeR2Unaa5vj+P0LOEoraIwQtKdokYotu84HUgrEUjiltjTOR1G1Rp0ughXq6ilX2IWbBlpLjYkSD9665smfSoiDFV/DLvQjKpzzq1N004gknNc07ix49Fc6ryiA2dqILslIhX0pCgXSTiJ2oarBaUAIkVltbE9mPQyt51DbbanHFmEpSJJ9qveC+COJccv3LdhQaaYc8u6ujlLahlSEfxrGxjANegeGvBlvaoUpK1l4iF3MZHUI6e/KtvY2Ftw+0atbRpLNu0kJbbRskf19d69lqv6d0s/LopPDngvg/hpBVYsS+R6n3TqWe0/pHYRWjCIpwQAKWMUvAi5NvYNQAFRHM+1S1nrURxQHOoyZSB5x448Cp4kV8S4W2EXwy40MJe79lfvXkTpU26pCgoLmFJIynse9fTLxSoGeYry/+0Lwuh5tfGLNH5qM3IH60/xe459aphz0+LLyxc1fs80kKEAZoDh0O6uRwYp5JSMe1DclQI512+jmHtPrafS62oocQZStBKVJ9iMj5VvuA/2scc4cEtX4b4mwk7uHQ6B/3AQfmPnXmqVHVvRw56e/M0jhGXYzPongv9ovh3jgS0bv8Fcq/wAC7hsk9lfCr5GtC7aIdUCSD0718sJVjSqCOYORFW/CfFHGOAqT/d3Enrdsbsk6mj/oVI+kVGfj3tBjJx6Po8WDf8IwKVVqhLZTAgjavLeD/wBsziFBvjfDUqQd7iyOfctqP7H5VuOHeNPD3GyEWHF7Zbp/wXFeW5/8FQa55QcfRRTk/YPiVq2jVpRBGZB3rynxPwxFs6blkDy1TqSP0mvZrxvWlWoRI51jOO8HNylaUgKE7TUE+LO/E1JUzx9xJk9zApmkg1oOJ+HLyxHmqZUWTssCY7HpVO62E4PKuuMkycouPZFSp1pwracKVbe46GkXcXBMqdmDsMCnlPqMUJ6RimpWTY3z7jzi6l9xtyMKQopj27U911+7fD1xdPPO/wDuOLKlfWoxVJ6xijNETFNX6FVMkoCjBJUQCMTjFTGCArIkVFQU7U/zAmM7UtD2kWyUiN/pRkrSlME455qnN+hCYUqJzNV9zxgqMNZ7mmURJSRd8R4qi2ZPNZ+FPWsk66t1xTi1FSyZJpFuLeUpbiipR5zyph71VKiL2O+LnEUiuvWuTvSnamAN7U7GkCmRXDeKAQkmnCdETB6jehAiOnyp6TvmsCj0Th3FPPtWXFHKkAn3irVp8KGSMjI5GsLwi5Um2CdRwTHarxm8UDuRnaoTSOiEVJbLO/tHUgKbAW2o7ndJ6e1V7dktTgCvtV1w66Q56FgFChCh2qQhkIvS0RtmevQ1xT+nRweRi4O10QbWwebVGSDkVPZt3fNGr4egq8atGwgKmaI2lvVBia48mSmRj1siJZDKNRGBUZ29ShyAIFWb6h5agYis+5bqKyScTzpFLloDVHtFpbpt7dDSdgPqakimjanV7kd7LC0h2paYVQKMnSMCeOIqtfd0jepb7m+cmqa7dOlRJkftXFkkdmCAN98ZMzjaqHiN8PLgEEASRGKNc3BkgQAfvWb4o+S2cA9p3qS2z0IxSPN+M2qbLiK2kiGlepAA2HT5VXK57gjNXnHUl0a91Iz8qopPWfevWxSco7PNzx4zdAHZSsL67in7iScAYikXmRAz0prS4BSScbU5LsMk4g4rivJE/SmxnaCa4wMUwBSoiAMChrhSYWAoDYEU4zOJHKmmCRQCix4d4j43wdIFhxW8YQP8LzCtH/xVI+1aBj+1LjSEab61srwYlQSWVf8A8yPtWNUe24oRAIM5FSlhhLtFY5JLo9LY/tVslNqRc8FuIUIVoeQsEexisjxLi/DX7txy0Q+0yoylDqRKe2Caz5+HpTNySBHzpIYIxeinzTaotXLxhZw5z5g0B66ZXBC9h0qAdVduIqiihHOTDB7nmOdKm5Uk4A+dBAJwN6cE6gTBBFNQt0GVevnZQHYChqfdVOpaojrQog1x3nG1aka7OOfUTmumSATSQa7Ao0AXPMD50nWlJmMACOX71x35/KsY4YIkfKlEkfF96aZmaWSRWMdsYO9dtSqxSASIrBR3OlTE5+dJONtqQb0DFrw5cNq/7pq4acmIJnrVHYH0qT0M71bNHONqjMvj6LmzfLbiVYwc1rLNxu6YQ6owW8EnmP8AzWKYVBFaLhTiXCWFbOpKD/KubLG0HNDlCjSIuWkApbXqO2M1GU84XSfhHI0nD7fSnKYOxo7lsc15jjZ47Y1vUtJKlExQHG4WfUADsDUxlkpHSgXg8vSDj5UYxAz1wU6aYKUziNudespUdLQpNBdURRTtUdzY+9LJjRWyDcLyc1SXrh+EA9Yq7fEzG21Ul1uocgN65ZnpYSiuVlRUSPTNZ/iOSRJzzrR3SPUr0iR+1Ud4hKiQse/tWjo6TGX6DqUk4Bms0U6HVo/hJA9q2N+yDODjnWVv29D6VjY+k16GGRweRH2RiKjqlKwqJzUo/ao7oI5jFdLOVBUqB0xmlG8dKC0og6eVGEFXOigCEbGRJ5CkO29LtMfam8z/AFFYIkAHehqIOaJEielDjGRQCMVmKGQNpHSiR9BTCJoBQ2J51w3p+gxIj2FPQj2J3rINnIRG4MxRY9O32rkggRNKTBoiA1iRlNAODBiOVHUBvNAPxVmFDScYpZgf7iuI61wPf/igMJuRzpeUfea4ARzn2rsiciaxhJJpRtE0hzXZ61jDsQQT3pu5p364PTY0nPMyKxhNsUo3pDsOvOurBJdgqLgJ/ixV40MCazrSy2tKx+kzWkbON6lkWymNktsnl9ateGuaHE5yIzVS0doIFTrZcKBHzqDOhOzcMOEAKlOk5qStZUkEjFVtg+ldoNUSgxMUW4vNX5SMTXnTXFs8fLDjNol/imkpyQIqi4rel10BMQOdEdUUk6hMYqEhvzVKmKWJFs92TT5oSTT69CzsZyutAdzRiZoDhJxQkxo9kJ7mKq7pI0kRGNhVm9Ik8qrLk4PICueR3YyjvGiNSlAkTzO9Ud+lITJV6iI2kVfXUkqwaor4mY+U0EdKejPXjfpOc5rJ8VZ1NrI3BmK2V1BB0iegFZy/b1BQINdmJ0QzK0Z9tWpsHE0JwTMU9uULW2QZBxXOYiu5O0ee9Mi5Ch1FHSvUJ5mgq+KlaWUrjrQWg0GBnETXECYPKnGI3+lJOZP3pgDTP0oah7zRTkmhqExvWMCO/Yda7aJPKf8Az3pVbnHOkHWlGRwGI+8dqIB2+lMERtREjOJ2zRAx47daWBJim4B+E079O2aIAatomgLAmpC8iDFRlmT8qDDEacQd4pVE47bdvakxGSKMGF6dXLEfOgGwIgHGIyaU55jH1pSClWftST6dyc1giGZ3wK45NcOR50hGaxhwwfflXKnOeddTgnGABWMD6VxwdxSmP96SCB8qwRwxFaCyX5jCFdorPgSqrjhTn5Skb6VY+dJNasfH+RcNDMiMVLaUMbTtUJFSW1dq5mdKNLwtxSmloGSUyPcUUh5atREDrVfwp7RcIM+mRWvfsmgzgfFXF5K9nn+XD7WULqVkhJMzvXJbLYBEZqbcaG4SFZqM46JgHArnWzjSV7PZkmdqeTQmzmnyK9E62jiajOc4oqlSYiguGQaDY8EQnjJMx7VW3ROdImrJ47iqu5OIA+dQkd2NFPdqKCdJjO471n7tYTqAIME5mSaub31DPWMnc1QXZ3RA23IrRLoqX1hJkGcddqqLoBQiY+dT7klM4kxt/Oqx9W9dMFRGZnrgeXfBR2Vg0xxOKPxIZSroqhLie0V3Qdo4JrZGcHOhjNFWMTQvfeszIO2oKTPMbiKeZiAJqOhelUk1IO9MuhTiZgc6aSADABkcxMc8dDiPmacQAeuKaRiaJgS/iP2oZ+LFFOwzQjigxkO7U5MjA500fenCJgSOdYDCgACTMzSxEnekSduhpTE70RQa/YVGV8RNSXJA96jK+I0GNETv9RMVM1Q2kdUxvUI4zTir09hWC0FjWTIoakkDr+9PaSSOs1y0GP8AagAGBIj+jSRGN6UnJmD2O9cBO0e9YYUfypQIGI70gECOdLzJ5d6xhpidx0pOlOAM5ikjB5VjCjrU3hiyLgp6pj6GoU9xPajW6vLebV0VmhLaoKdM0ratjP0o6DBic8qiNE0dJhXKuVnYi0s3IcGRnFbZN1rs2D/kGZ+VYC3XCt/btWnYW49w5lKFRBII+4rmzx5ROXy43Cye6kKzvVZchSFDSJoiFut+hckfxU5RSpKSNjXLXE8s9mTjE06T1pgP0p3XNdlnexijUdROd6Os4qM4RQZSCIzxgHaO9VV4oRIP23qwfVgjmdqqLtRn2qLeztxopb1UQk/FuaobxQQSSSParu9WVa458xyrO3ij5h9Rxg86eJUqLtwqW5HIYjpVa6etTn41GRBPeq5zIrpiQkVl+CppWeW1RAdbST1FTbvKVdKgNGWY5gxXVjZx5exqhQTE1JUJxQFiM1Rk0DIk1IbOpI6iaAMEURowSnqJoILDQDudqQyTApZxAnNduQYmmFBEA4ihLEe3OjkED50JY58jQCho5UQGDH1mhyRRE5kzvWCPHKnc9t9qQfKujlGe1EUG5gRFRzg9sipDm1RiZMxFD2PE7l3pBO5pSK750AkloQ2nmYpV8/vSNEltM07lOIM0RPYEpkTG3Sm9o5bUUg6topFNcxt0FANggfUew2p29JpAEk78prsf1zrBOjIz9abBByaeIO9NAxWCcTBEDPcU4cyDypudXX3pU7gn71jGit1BbaVjmJqSDt0qu4erXaozkSKnj+orlkqOyLtEllXqEb1rPD7qS28hwiICveKyDZjPKr7gjkOrQP1oIFSn+LEzx5Y2i8uChaSEpmq1xC2fhwDyqybEpBjUefI0x4JCtKkntXBtO2eKepJvUKOFCelSEPhWBXiTXjO9bfAUmUzyNegcC40u8ZSSDB6125ccsfZ60YwyLRr1K+1RnSeW/OkadkZrnNp6VO7RlHi6ITxySc86pb1ZBIJGkAmrh+YJ6iqS+9YcjA0mpM7IFPeujQT8O3Les3dkhWZPc1eXpHMfL71Q3isgqzVIFJFQ8Y5SetQXCMxg1PuRqUfeAKgOc66o9HNLsrbz4SOtVjU+YQOYJ/rvVpdyoHtVQhWlwe9XgcuQkEzFDWnHTrRiAFAdaGpOJNXokgBFOQdKx9M0ik0iY1gc96VBJJriCRSpHU0hzk0wBJxvNDWZB2PWigx7UxYmsZAQDvGNt6eOW1MMZPyp6d+8UAsKkGaWDM85k4pAc4HbNKc0RQLu8EYFR+p3o7mZ77VH1wBvtSvsdCn4fvXD5VxEk4HWlnJnaJ+VYJIZygiYg0Q7TmJzQWDhU9eVGKsCmQj7GGCRP0mnJABro++aU4wawBjrerIEK+lA+UQYqVMwOlBcEAkUGhkM5fyroACQPnjb588fSkAk/elAMHsJoBEAgj60qQZjlTilQbCzGk6tv8ommyZ5VjFrwtUtLT0VP1qzSMA1S8LUfxBRMBSZq7SMSahPs6sT0PSTNXHBlhF41qP6tOKqE5gjep9gSH0K3yDUZKyklaNKm5EaQiFA5zQXvzSJmakvMhBJ3nNR2hqcWOQxXBLG1s8BunTP
  Category:
    type: object
    properties:
      categoryName:
        type: string
    example:
      categoryName: People
  Difficulty:
    type: object
    properties:
      difficultyName:
        type: string
      timeSpan:
        type: integer
        format: Int32
    example:
      difficultyName: Hard
      timeSpan: 10
  Error:
    type: object
    properties:
      Error:
        type: string
    example:
      Error: This is a sample error message